### ISSUE TITLE
youtube-dl update

### ISSUE THREAD

**Issue by cmnord** [Jessime/youtube_history#1]
I couldn't log in using youtube-dl until I upgraded youtube-dl to version 2016.11.22 (see [this issue](https://github.com/rg3/youtube-dl/issues/11270))

**Comment by Jessime** [comment]
Thanks for reporting this! There was no good justification for specifying specific versions other than that's the default output of `pip freeze`. I've updated the `requirements.txt` file so the latest version of each package will be installed (https://github.com/Jessime/youtube_history/commit/84632f5fd95d15864b2dd38c08471f89bb0afff5). I just tested it out on my laptop. 

youtube-dl's nightly build installs and allows me to login to Google without issue.

Hopefully everything's working smoothly for you now, but please let me know if it isn't!

**Comment by Motuzkov** [comment]
Still cant enter password while login :(
input line is inactive

**Comment by Jessime** [comment]
@Motuzkov If I understand you correctly, the password text isn't showing on screen, correct? 

That's actually how it's supposed to work, so nobody can see your password. Just type your password-- even though you won't see anything happen-- and hit enter.

**Comment by Motuzkov** [comment]
@Jessime Im sorry for that fail :D Thank you very much! Have a good day

**Comment by Jessime** [comment]
@Motuzkov No problem! It's worth noting that the problem that caused cmnord to not be able to login is still an open issue on the youtube-dl repository. If you're sure that you enter your password correctly but you're still not able to get data, please let me know.
