### ISSUE TITLE
Unclear whether you need html, json or both formats from takeout

### ISSUE THREAD

**Issue by felciano** [Jessime/youtube_history#12]
When requesting Youtube data via takeout, there appears to be an option for the history data to be provided in either `html` or `json` format. This produces both the `watch-history` and `search-history` files in that format. `youtube_history` seems to want one of them in `html` format and the other in `json` format--is that correct? So do you need to do two passes through takeout to get both formats?

**Comment by Jessime** [comment]
Hey! Does this edit to the README make things clear enough? https://github.com/Jessime/youtube_history/commit/3b2ed1643b12a7fc1f5891e678af8f74e6a3c286

I don't do anything with the search history file (though, maybe that would be an interesting addition).

**Comment by felciano** [comment]
It does, thank you. Closing this as resolved.

Out of curiosity, why did you decide to parse/scrape the raw html instead of just reading in from the json version of the history?

**Comment by Jessime** [comment]
I wish I had a good answer for you, but I think I just came across the html format first, haha.
