### ISSUE TITLE
Can't login ( NameError: name 'myaccountname' is not defined )

### ISSUE THREAD

**Issue by Yakume** [Jessime/youtube_history#3]
Hi, I can't log in with my google name, I try with the email or without using spaces but the result is the same, what I'm doing wrong ?
I exec "python youtube_history.py" and write the name but after that it gives me that error.

P.S. Thanks for your work :D

**Comment by Jessime** [comment]
Hey! I think you're using Python 2 instead of Python 3. Is that the case?

**Comment by Yakume** [comment]
Hi, you are right, I was using python 2 so I used "python3 youtube_history.py" command but now it gives me this error : 
"import pandas as pd
ImportError: No module named 'pandas'"

(sorry for the late answer)

**Comment by Jessime** [comment]
You don't have the required dependencies installed in python3. Doing `pip3 install -r requirements.txt` from the project folder should clear this up.

**Comment by Yakume** [comment]
Now is going, thank you for your support and for this script :D

**Comment by Jessime** [comment]
Great! I'm going to close this issue. Feel free to open another one if something else comes up.
