### ISSUE TITLE
Stops running

### ISSUE THREAD

**Issue by jjousun** [Jessime/youtube_history#4]
Thanks so much for this!

I have a problem where the program is running in the terminal and then it stops. The first time it stopped around video 1081 out of 2049. The second time it stopped around video 588 out of 2049.

Do you know what the issue might be?

**Comment by Jessime** [comment]
Thanks! Sorry you're having trouble with it. 

This isn't an issue I've run into or had anyone mention before. Without more information I'd have to guess that it's an internet connection issue. 

Do you get any error output from the app? If so, what does it say?

**Comment by jjousun** [comment]
![image](https://user-images.githubusercontent.com/13179407/27850723-5ee4c074-610b-11e7-87dd-3e4e332bf2d0.png)

This is what the terminal looks like. After the line `[youtube] xfVPU3LAm0E: Downloading webpage`
it hangs there with no message.

After I force it to terminate, then I get the last chunk of code.

**Comment by Jessime** [comment]
Would you mind running it again? I wonder if you'll end up getting stuck on one of those two videos again. What are the chances that those are "Live" videos? https://github.com/rg3/youtube-dl/issues/12271

If you run it again, keep an eye on your connectivity and see if the connection gets weak or anything like that.

**Comment by jjousun** [comment]
So I let it run overnight and turned off the option to let the computer sleep. That did the trick!

How can I see the DataFrame and/or the downloaded JSON files? For my project I'm trying to work with only YouTube videos that are music (tagged 'music' in the Category section). So I was thinking I would have to clean up/filter the data after youtube-dl got all of it, but am not sure if it's possible or if how to do it. Any ideas?

**Comment by Jessime** [comment]
Awesome!

You can find your DataFrame at `your/path/to/youtube_history/data/ran/df.csv`. It should be fairly easy to grab the music related videos from the DataFrame if you have experience with pandas.

**Comment by jjousun** [comment]
Thanks again so much! I really appreciate all your help.

What would you suggest if I don't have experience with pandas (I'm new to Python all together)? Do you think I should just tinker around with it anyway? How would I do that?

**Comment by Jessime** [comment]
Well, that makes it more challenging, but I'd definitely recommend giving it a shot. Here are three recommendations to get you started.

1. In your terminal, type `jupyter notebook` to launch the Jupyter Notebook. It's a great way to code in Python, especially if you're doing exploratory data analysis. 

2. [Here are some Pandas tutorials](https://pandas.pydata.org/pandas-docs/stable/tutorials.html) to get you started learning pandas syntax.

3. And if you have questions as you go along, [r/learnpython](https://www.reddit.com/r/learnpython/new/) will be happy to answer even your most basic/beginner questions. But make sure you can demonstrate that you've put effort into figuring out the answer for yourself first.

I hope this helps!
